CREATE TABLE TabelaDep ( -- 1ª
	COD_DEPTO INT IDENTITY NOT NULL, -- PK_TabelaDep
	DEPTO VARCHAR(100) NOT NULL,

	CONSTRAINT PK_TabelaDep PRIMARY KEY (COD_DEPTO),
)

--DROP TABLE TabelaDep

--SELECT * FROM TabelaDep

--INSERT INTO TabelaDep (DEPTO) VALUES ('TI')
--INSERT INTO TabelaDep (DEPTO) VALUES ('RH')
--INSERT INTO TabelaDep (DEPTO) VALUES ('PRODUÇÃO')
--INSERT INTO TabelaDep (DEPTO) VALUES ('ADIMINISTRAÇÃO')

--------------------------------------------------------------------------------------

CREATE TABLE TabelaCar ( -- 2ª
	COD_CARGO INT IDENTITY NOT NULL, -- PK_TabelaCar
	CARGO VARCHAR(100) NOT NULL,
	SALARIO_INIC DECIMAL(10,2) NOT NULL,

	CONSTRAINT PK_TabelaCar PRIMARY KEY (COD_CARGO)
)

--DROP TABLE TabelaCar

--SELECT * FROM TabelaCar

--INSERT INTO TabelaCar (CARGO, SALARIO_INIC) VALUES ('ESTÁGIÁRIO', 1100.00)
--INSERT INTO TabelaCar (CARGO, SALARIO_INIC) VALUES ('JÚNIOR', 1500.00)
--INSERT INTO TabelaCar (CARGO, SALARIO_INIC) VALUES ('SÊNIOR', 3000.00)
--INSERT INTO TabelaCar (CARGO, SALARIO_INIC) VALUES ('TÉCNICO', 3000.00)
--INSERT INTO TabelaCar (CARGO, SALARIO_INIC) VALUES ('GESTOR', 5000.00)
--INSERT INTO TabelaCar (CARGO, SALARIO_INIC) VALUES ('DIRETOR', 10000.00)

--------------------------------------------------------------------------------------

CREATE TABLE Empregados ( -- 3ª
	CODFUN INT IDENTITY NOT NULL, -- PK_Empregados
	NOME VARCHAR(200) NOT NULL,
	NUM_DEPEND INT,
	DATA_NASCIMENTO DATE,
	COD_DEPTO INT NOT NULL, -- FK_TabelaDep
	COD_CARGO INT NOT NULL, -- FK_TabelaCar
	DATA_ADMISSAO DATE,
	SALARIO DECIMAL(10,2) NOT NULL,
	SINDICALIZADO VARCHAR(10),
	OBS VARCHAR(1000),

	CONSTRAINT PK_Empregados PRIMARY KEY (CODFUN),
	CONSTRAINT FK_TabelaDep FOREIGN KEY (COD_DEPTO) REFERENCES TabelaDep (COD_DEPTO),
	CONSTRAINT FK_TabelaCar FOREIGN KEY (COD_CARGO) REFERENCES TabelaCar (COD_CARGO),
)

--DROP TABLE Empregados

--SELECT * FROM Empregados

--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('PEDRO', 1, 1, 4, 3000.00) -- 1
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('EMMA', 0, 2, 5, 5000.00)
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('JOAO', 0, 3, 6, 12000.00)
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('PAULO', 0, 4, 1, 1100.00)
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('RITA', 1, 1, 2, 2000.00) -- 5
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('JOANA', 2, 2, 3, 3000.00) -- 6
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('ROBERTA', 0, 3, 4, 4000.00)
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('AUGUSTO', 0, 4, 5, 7000.00)
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('FELIPE', 1, 1, 6, 11000.00) -- 9
--INSERT INTO Empregados (NOME, NUM_DEPEND, COD_DEPTO, COD_CARGO, SALARIO) VALUES ('SAMUEL', 2, 2, 1, 1200.00) -- 10

--------------------------------------------------------------------------------------

CREATE TABLE Dependentes ( -- 4ª
	CODFUN INT NOT NULL, -- FK_Empregados
	CODDEP INT IDENTITY NOT NULL, -- PK_Dependentes
	NOME VARCHAR(200) NOT NULL,
	DATA_NASCIMENTO DATE,

	CONSTRAINT PK_Dependentes PRIMARY KEY (CODDEP),
	CONSTRAINT FK_Empregados FOREIGN KEY (CODFUN) REFERENCES Empregados (CODFUN),
)

--DROP TABLE Dependentes

--SELECT * FROM Dependentes

--INSERT INTO Dependentes (CODFUN, NOME) VALUES (1, 'JOAQUIM')
--INSERT INTO Dependentes (CODFUN, NOME) VALUES (5, 'ANA')
--INSERT INTO Dependentes (CODFUN, NOME) VALUES (6, 'LIA')
--INSERT INTO Dependentes (CODFUN, NOME) VALUES (6, 'DOUGLAS')
--INSERT INTO Dependentes (CODFUN, NOME) VALUES (9, 'HAMILTON')
--INSERT INTO Dependentes (CODFUN, NOME) VALUES (10, 'CARLOS')
--INSERT INTO Dependentes (CODFUN, NOME) VALUES (10, 'HUDSON')