use db_vendas
-- 1
SELECT TOP 6 * FROM TB_CLIENTE
-- 2
SELECT 
	DESCRICAO, 
	ID_PRODUTO, 
	QTD_REAL, 
	QTD_MINIMA,
	(QTD_REAL - QTD_MINIMA) AS [qtd acima em estoque]
FROM TB_PRODUTO
-- 3
SELECT TOP 1 * FROM TB_PRODUTO 
WHERE DESCRICAO LIKE 'O%' AND PRECO_CUSTO > 0 ORDER BY QTD_REAL
-- 4 
SELECT * FROM TB_PEDIDO
WHERE YEAR(DATA_EMISSAO) = 2019 AND SITUACAO = 'C'
ORDER BY CODVEN DESC, NUM_PEDIDO DESC